---
- name: "Update the wifi configuration"
  template:
    src: "etc/wpa_supplicant/wpa_supplicant.conf.j2"
    dest: "/etc/wpa_supplicant/wpa_supplicant.conf"
    owner: "root"
    group: "root"
    mode: "u=rw,g=,o="
  notify: "restart networking"
